### ISSUE TITLE
例外発生:FileNotFoundException

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#256]
[240114221904710][Enforcement]例外発生:\r\n- Type ------\r\nFileNotFoundException\r\n- Message ------\r\nCould not find file 'F:\存储器备份\2022.6.7 megagrrl 32gb\VGMRips\OPNA\Doukyusei_2_(NEC_PC-9801)\01 Elf Logo.vgz'.\r\n- Source ------\r\nSystem.Private.CoreLib\r\n- StackTrace ------\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at MDPlayer.PlayList.AddFilexxx(Int32& index, Music mc, Object entry)\r\n
[240114221904756][Enforcement]例外発生:\r\n- Type ------\r\nFileNotFoundException\r\n- Message ------\r\nCould not find file 'F:\存储器备份\2022.6.7 megagrrl 32gb\VGMRips\OPNA\Doukyusei_2_(NEC_PC-9801)\02 Sweet on You.vgz'.\r\n- Source ------\r\nSystem.Private.CoreLib\r\n- StackTrace ------\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at MDPlayer.PlayList.AddFilexxx(Int32& index, Music mc, Object entry)\r\n
[240114221904767][Enforcement]例外発生:\r\n- Type ------\r\nFileNotFoundException\r\n- Message ------\r\nCould not find file 'F:\存储器备份\2022.6.7 megagrrl 32gb\VGMRips\OPNA\Doukyusei_2_(NEC_PC-9801)\03 Sky of The City.vgz'.\r\n- Source ------\r\nSystem.Private.CoreLib\r\n- StackTrace ------\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at MDPlayer.PlayList.AddFilexxx(Int32& index, Music mc, Object entry)\r\n
[240114221904778][Enforcement]例外発生:\r\n- Type ------\r\nFileNotFoundException\r\n- Message ------\r\nCould not find file 'F:\存储器备份\2022.6.7 megagrrl 32gb\VGMRips\OPNA\Doukyusei_2_(NEC_PC-9801)\04 Let's Go Big.vgz'.\r\n- Source ------\r\nSystem.Private.CoreLib\r\n- StackTrace ------\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at MDPlayer.PlayList.AddFilexxx(Int32& index, Music mc, Object entry)\r\n
[240114221904794][Enforcement]例外発生:\r\n- Type ------\r\nFileNotFoundException\r\n- Message ------\r\nCould not find file 'F:\存储器备份\2022.6.7 megagrrl 32gb\VGMRips\OPNA\Doukyusei_2_(NEC_PC-9801)\05 Honey Night.vgz'.\r\n- Source ------\r\nSystem.Private.CoreLib\r\n- StackTrace ------\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at MDPlayer.PlayList.AddFilexxx(Int32& index, Music mc, Object entry)\r\n
[240114221904809][Enforcement]例外発生:\r\n- Type ------\r\nFileNotFoundException\r\n- Message ------\r\nCould not find file 'F:\存储器备份\2022.6.7 megagrrl 32gb\VGMRips\OPNA\Doukyusei_2_(NEC_PC-9801)\06 New Year.vgz'.\r\n- Source ------\r\nSystem.Private.CoreLib\r\n- StackTrace ------\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at MDPlayer.PlayList.AddFilexxx(Int32& index, Music mc, Object entry)\r\n
[240114221904828][Enforcement]例外発生:\r\n- Type ------\r\nFileNotFoundException\r\n- Message ------\r\nCould not find file 'F:\存储器备份\2022.6.7 megagrrl 32gb\VGMRips\OPNA\Doukyusei_2_(NEC_PC-9801)\07 Pleasant Journey.vgz'.\r\n- Source ------\r\nSystem.Private.CoreLib\r\n- StackTrace ------\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at MDPlayer.PlayList.AddFilexxx(Int32& index, Music mc, Object entry)\r\n
[240114221904843][Enforcement]例外発生:\r\n- Type ------\r\nFileNotFoundException\r\n- Message ------\r\nCould not find file 'F:\存储器备份\2022.6.7 megagrrl 32gb\VGMRips\OPNA\Doukyusei_2_(NEC_PC-9801)\08 BGM 1.vgz'.\r\n- Source ------\r\nSystem.Private.CoreLib\r\n- StackTrace ------\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at MDPlayer.PlayList.AddFilexxx(Int32& index, Music mc, Object entry)\r\n
[240114221904859][Enforcement]例外発生:\r\n- Type ------\r\nFileNotFoundException\r\n- Message ------\r\nCould not find file 'F:\存储器备份\2022.6.7 megagrrl 32gb\VGMRips\OPNA\Doukyusei_2_(NEC_PC-9801)\09 BGM 2.vgz'.\r\n- Source ------\r\nSystem.Private.CoreLib\r\n- StackTrace ------\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at MDPlayer.PlayList.AddFilexxx(Int32& index, Music mc, Object entry)\r\n
[240114221904874][Enforcement]例外発生:\r\n- Type ------\r\nFileNotFoundException\r\n- Message ------\r\nCould not find file 'F:\存储器备份\2022.6.7 megagrrl 32gb\VGMRips\OPNA\Doukyusei_2_(NEC_PC-9801)\10 BGM 3.vgz'.\r\n- Source ------\r\nSystem.Private.CoreLib\r\n- StackTrace ------\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at MDPlayer.PlayList.AddFilexxx(Int32& index, Music mc, Object entry)\r\n
[240114221904890][Enforcement]例外発生:\r\n- Type ------\r\nFileNotFoundException\r\n- Message ------\r\nCould not find file 'F:\存储器备份\2022.6.7 megagrrl 32gb\VGMRips\OPNA\Doukyusei_2_(NEC_PC-9801)\11 Misako's Theme.vgz'.\r\n- Source ------\r\nSystem.Private.CoreLib\r\n- StackTrace ------\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at MDPlayer.PlayList.AddFilexxx(Int32& index, Music mc, Object entry)\r\n
[240114221904906][Enforcement]例外発生:\r\n- Type ------\r\nFileNotFoundException\r\n- Message ------\r\nCould not find file 'F:\存储器备份\2022.6.7 megagrrl 32gb\VGMRips\OPNA\Doukyusei_2_(NEC_PC-9801)\12 Yui's Theme.vgz'.\r\n- Source ------\r\nSystem.Private.CoreLib\r\n- StackTrace ------\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at MDPlayer.PlayList.AddFilexxx(Int32& index, Music mc, Object entry)\r\n
[240114221904922][Enforcement]例外発生:\r\n- Type ------\r\nFileNotFoundException\r\n- Message ------\r\nCould not find file 'F:\存储器备份\2022.6.7 megagrrl 32gb\VGMRips\OPNA\Doukyusei_2_(NEC_PC-9801)\13 Sakurako's Theme.vgz'.\r\n- Source ------\r\nSystem.Private.CoreLib\r\n- StackTrace ------\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at MDPlayer.PlayList.AddFilexxx(Int32& index, Music mc, Object entry)\r\n
[240114221904937][Enforcement]例外発生:\r\n- Type ------\r\nFileNotFoundException\r\n- Message ------\r\nCould not find file 'F:\存储器备份\2022.6.7 megagrrl 32gb\VGMRips\OPNA\Doukyusei_2_(NEC_PC-9801)\14 Tomomi's Theme.vgz'.\r\n- Source ------\r\nSystem.Private.CoreLib\r\n- StackTrace ------\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at MDPlayer.PlayList.AddFilexxx(Int32& index, Music mc, Object entry)\r\n
[240114221904953][Enforcement]例外発生:\r\n- Type ------\r\nFileNotFoundException\r\n- Message ------\r\nCould not find file 'F:\存储器备份\2022.6.7 megagrrl 32gb\VGMRips\OPNA\Doukyusei_2_(NEC_PC-9801)\15 Karen's Theme.vgz'.\r\n- Source ------\r\nSystem.Private.CoreLib\r\n- StackTrace ------\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at MDPlayer.PlayList.AddFilexxx(Int32& index, Music mc, Object entry)\r\n
[240114221904968][Enforcement]例外発生:\r\n- Type ------\r\nFileNotFoundException\r\n- Message ------\r\nCould not find file 'F:\存储器备份\2022.6.7 megagrrl 32gb\VGMRips\OPNA\Doukyusei_2_(NEC_PC-9801)\16 Mirei's Theme.vgz'.\r\n- Source ------\r\nSystem.Private.CoreLib\r\n- StackTrace ------\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at MDPlayer.PlayList.AddFilexxx(Int32& index, Music mc, Object entry)\r\n
[240114221904983][Enforcement]例外発生:\r\n- Type ------\r\nFileNotFoundException\r\n- Message ------\r\nCould not find file 'F:\存储器备份\2022.6.7 megagrrl 32gb\VGMRips\OPNA\Doukyusei_2_(NEC_PC-9801)\17 Azumi's Theme.vgz'.\r\n- Source ------\r\nSystem.Private.CoreLib\r\n- StackTrace ------\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at MDPlayer.PlayList.AddFilexxx(Int32& index, Music mc, Object entry)\r\n
[240114221904999][Enforcement]例外発生:\r\n- Type ------\r\nFileNotFoundException\r\n- Message ------\r\nCould not find file 'F:\存储器备份\2022.6.7 megagrrl 32gb\VGMRips\OPNA\Doukyusei_2_(NEC_PC-9801)\18 Kozue's Theme.vgz'.\r\n- Source ------\r\nSystem.Private.CoreLib\r\n- StackTrace ------\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at MDPlayer.PlayList.AddFilexxx(Int32& index, Music mc, Object entry)\r\n
[240114221905015][Enforcement]例外発生:\r\n- Type ------\r\nFileNotFoundException\r\n- Message ------\r\nCould not find file 'F:\存储器备份\2022.6.7 megagrrl 32gb\VGMRips\OPNA\Doukyusei_2_(NEC_PC-9801)\19 Izumi's Theme.vgz'.\r\n- Source ------\r\nSystem.Private.CoreLib\r\n- StackTrace ------\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at MDPlayer.PlayList.AddFilexxx(Int32& index, Music mc, Object entry)\r\n
[240114221905030][Enforcement]例外発生:\r\n- Type ------\r\nFileNotFoundException\r\n- Message ------\r\nCould not find file 'F:\存储器备份\2022.6.7 megagrrl 32gb\VGMRips\OPNA\Doukyusei_2_(NEC_PC-9801)\20 Misa's Theme.vgz'.\r\n- Source ------\r\nSystem.Private.CoreLib\r\n- StackTrace ------\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at MDPlayer.PlayList.AddFilexxx(Int32& index, Music mc, Object entry)\r\n
[240114221905046][Enforcement]例外発生:\r\n- Type ------\r\nFileNotFoundException\r\n- Message ------\r\nCould not find file 'F:\存储器备份\2022.6.7 megagrrl 32gb\VGMRips\OPNA\Doukyusei_2_(NEC_PC-9801)\21 Minori's Theme.vgz'.\r\n- Source ------\r\nSystem.Private.CoreLib\r\n- StackTrace ------\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at MDPlayer.PlayList.AddFilexxx(Int32& index, Music mc, Object entry)\r\n
[240114221905061][Enforcement]例外発生:\r\n- Type ------\r\nFileNotFoundException\r\n- Message ------\r\nCould not find file 'F:\存储器备份\2022.6.7 megagrrl 32gb\VGMRips\OPNA\Doukyusei_2_(NEC_PC-9801)\22 Hiroko's Theme.vgz'.\r\n- Source ------\r\nSystem.Private.CoreLib\r\n- StackTrace ------\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at MDPlayer.PlayList.AddFilexxx(Int32& index, Music mc, Object entry)\r\n
[240114221905073][Enforcement]例外発生:\r\n- Type ------\r\nFileNotFoundException\r\n- Message ------\r\nCould not find file 'F:\存储器备份\2022.6.7 megagrrl 32gb\VGMRips\OPNA\Doukyusei_2_(NEC_PC-9801)\23 Misato's Theme.vgz'.\r\n- Source ------\r\nSystem.Private.CoreLib\r\n- StackTrace ------\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at MDPlayer.PlayList.AddFilexxx(Int32& index, Music mc, Object entry)\r\n
[240114221905085][Enforcement]例外発生:\r\n- Type ------\r\nFileNotFoundException\r\n- Message ------\r\nCould not find file 'F:\存储器备份\2022.6.7 megagrrl 32gb\VGMRips\OPNA\Doukyusei_2_(NEC_PC-9801)\24 Sachiko's Theme.vgz'.\r\n- Source ------\r\nSystem.Private.CoreLib\r\n- StackTrace ------\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at MDPlayer.PlayList.AddFilexxx(Int32& index, Music mc, Object entry)\r\n
[240114221905101][Enforcement]例外発生:\r\n- Type ------\r\nFileNotFoundException\r\n- Message ------\r\nCould not find file 'F:\存储器备份\2022.6.7 megagrrl 32gb\VGMRips\OPNA\Doukyusei_2_(NEC_PC-9801)\25 Yoko's Theme.vgz'.\r\n- Source ------\r\nSystem.Private.CoreLib\r\n- StackTrace ------\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at MDPlayer.PlayList.AddFilexxx(Int32& index, Music mc, Object entry)\r\n
[240114221905117][Enforcement]例外発生:\r\n- Type ------\r\nFileNotFoundException\r\n- Message ------\r\nCould not find file 'F:\存储器备份\2022.6.7 megagrrl 32gb\VGMRips\OPNA\Doukyusei_2_(NEC_PC-9801)\26 Kumiko's Theme.vgz'.\r\n- Source ------\r\nSystem.Private.CoreLib\r\n- StackTrace ------\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at MDPlayer.PlayList.AddFilexxx(Int32& index, Music mc, Object entry)\r\n
[240114221905133][Enforcement]例外発生:\r\n- Type ------\r\nFileNotFoundException\r\n- Message ------\r\nCould not find file 'F:\存储器备份\2022.6.7 megagrrl 32gb\VGMRips\OPNA\Doukyusei_2_(NEC_PC-9801)\27 Miyuki's Theme.vgz'.\r\n- Source ------\r\nSystem.Private.CoreLib\r\n- StackTrace ------\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at MDPlayer.PlayList.AddFilexxx(Int32& index, Music mc, Object entry)\r\n
[240114221905149][Enforcement]例外発生:\r\n- Type ------\r\nFileNotFoundException\r\n- Message ------\r\nCould not find file 'F:\存储器备份\2022.6.7 megagrrl 32gb\VGMRips\OPNA\Doukyusei_2_(NEC_PC-9801)\28 Yoshiki's Theme.vgz'.\r\n- Source ------\r\nSystem.Private.CoreLib\r\n- StackTrace ------\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at MDPlayer.PlayList.AddFilexxx(Int32& index, Music mc, Object entry)\r\n
[240114221905169][Enforcement]例外発生:\r\n- Type ------\r\nFileNotFoundException\r\n- Message ------\r\nCould not find file 'F:\存储器备份\2022.6.7 megagrrl 32gb\VGMRips\OPNA\Doukyusei_2_(NEC_PC-9801)\29 Saionji's Theme.vgz'.\r\n- Source ------\r\nSystem.Private.CoreLib\r\n- StackTrace ------\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at MDPlayer.PlayList.AddFilexxx(Int32& index, Music mc, Object entry)\r\n
[240114221905185][Enforcement]例外発生:\r\n- Type ------\r\nFileNotFoundException\r\n- Message ------\r\nCould not find file 'F:\存储器备份\2022.6.7 megagrrl 32gb\VGMRips\OPNA\Doukyusei_2_(NEC_PC-9801)\30 Tendou's Theme.vgz'.\r\n- Source ------\r\nSystem.Private.CoreLib\r\n- StackTrace ------\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at MDPlayer.PlayList.AddFilexxx(Int32& index, Music mc, Object entry)\r\n
[240114221905201][Enforcement]例外発生:\r\n- Type ------\r\nFileNotFoundException\r\n- Message ------\r\nCould not find file 'F:\存储器备份\2022.6.7 megagrrl 32gb\VGMRips\OPNA\Doukyusei_2_(NEC_PC-9801)\31 Akira's Theme.vgz'.\r\n- Source ------\r\nSystem.Private.CoreLib\r\n- StackTrace ------\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at MDPlayer.PlayList.AddFilexxx(Int32& index, Music mc, Object entry)\r\n
[240114221905216][Enforcement]例外発生:\r\n- Type ------\r\nFileNotFoundException\r\n- Message ------\r\nCould not find file 'F:\存储器备份\2022.6.7 megagrrl 32gb\VGMRips\OPNA\Doukyusei_2_(NEC_PC-9801)\32 Ardent Love.vgz'.\r\n- Source ------\r\nSystem.Private.CoreLib\r\n- StackTrace ------\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at MDPlayer.PlayList.AddFilexxx(Int32& index, Music mc, Object entry)\r\n
[240114221905247][Enforcement]例外発生:\r\n- Type ------\r\nFileNotFoundException\r\n- Message ------\r\nCould not find file 'F:\存储器备份\2022.6.7 megagrrl 32gb\VGMRips\OPNA\Doukyusei_2_(NEC_PC-9801)\45 Chime.vgz'.\r\n- Source ------\r\nSystem.Private.CoreLib\r\n- StackTrace ------\r\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at MDPlayer.PlayList.AddFilexxx(Int32& index, Music mc, Object entry)\r\n

**Comment by kuma4649** [comment]
例外が発生して何か不都合がありましたか？
例外が記録される理由は色々あります。必ずしも不都合に繋がるものではありませんので。
この例外はファイルが読み込めなかったことを示しているだけです。
どういう状況でこれが記録されたのかわかりません。

例外のメッセージをただ載せるのではなく、
どのように操作したらどうなったといった経緯とか、
それによってどのような困った状況になったのかも書いてもらえませんか？

そろそろわかってほしいのですが、
私はなんでもわかったり、直せたりするわけではありません。
投げやり過ぎです。

**Comment by denjhang** [comment]
Please watch this video. I just drag VGZ into the playlist and these appear in the console.

**Comment by denjhang** [comment]
https://youtu.be/upfG-51kMqg

**Comment by kuma4649** [comment]
曲は鳴っているようですね。
であれば問題無いです。
気になる場合はコンソールを閉じてください。
大事なのは「コンソールで表示されるのはログである」ということです。
使用していて特に支障がない場合は、ログを気にする必要はありません。
